#a=open("sample.txt","x")
# b=open("sample.txt","w")
# b.write("Everything will be alright")
# b.write("\npython is a programming language")
# b.close()
# b=open("sample.txt","a")
# b.write("\nall is well")
# b.close()
# b=open("sample.txt","r")
# print(b.read())
# b.close()
# b=open("sample.txt","r")
# print(b.read(5))
# b.close()
# b=open("sample.txt","r")
# print(b.readline())
# print(b.readline())
# b.close()
# c=open("simple.txt","x")
# import os
# os.remove("simple.txt")

# os.rmdir("main")


a=open("fil1.txt","x")
b=open("fil1.txt","w")
b.write("My name is devanand")
b=open("fil1.txt","r")
x=b.read()

c=open("fil2.txt","x")
d=open("fil2.txt","w")
d.write(x)
d=open("fil2.txt","r")
print(d.read())

# l=open("fie1.txt","x")
n=open("fie1.txt","w")
n.write("good morning")
n=open("fie1.txt","r")
o=n.read()

# p=open("fie2.txt","x")
q=open("fie2.txt","w")
q.write("\nHave a nice day")
q=open("fie2.txt","r")
s=q.read()

# t=open("fie3.txt","x")
v=open("fie3.txt","w")
v.write(o)
v.write(s)
v=open("fie3.txt","r")
print(v.read())
